source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'ruby-openid'
gem 'open_id_authentication'
gem 'sqlite3'
group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'faker'
  gem 'simplecov', :require => false
  gem 'database_cleaner'
end

